language: go
go:
  - 1.7
go_import_path: code.cloudfoundry.org/cli
install:
  - go get -v github.com/onsi/ginkgo/ginkgo
script:  bin/test -nodes=2 -compilers=2
branches:
  only:
  - snapcraft
addons:
  code_climate:
    repo_token: 5a9ca60422d07f52c50f36aa2c2c101619a19aa64d94fdafb352746b1db8625e
env:
  - GIT_SSH="/tmp/ssh"
after_success:
  - echo -e '#!/bin/sh\n\nssh -o StrictHostKeyChecking=no $*' >> /tmp/ssh
  - chmod a+x /tmp/ssh
  - openssl aes-256-cbc -K $encrypted_6314a4c30201_key -iv $encrypted_6314a4c30201_iv
            -in .travis/deploy_key.enc -out .travis/deploy_key -d
  - chmod 600 .travis/deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add .travis/deploy_key
  - git remote add deploy git+ssh://snapbot@git.launchpad.net/cloudfoundry-cli
  - git push deploy $TRAVIS_BRANCH --force
